[book]
authors = ["niki"]
language = "zh"
multilingual = false
src = "src"
title = "niki'blog"
description= "niki'blog"

[output.html]
# defaulr dark theme
default-theme = "navy"
# for Chinese search
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/reference.js", "assets/highlight.js", "theme/pagetoc.js"]
additional-css = ["assets/utils.css", "theme/pagetoc.css"]
# set for github icon
git-repository-url = "https://github.com/sosocrown/obsidian2web"
git-repository-icon = "fa-github"
# set open math support
mathjax-support = true
